# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulation <- function(tsteps, mortality, demo, gt, K, dispersal, selfing, locus_effect, dominance_effect, phenotype_opt, n_p, n_k, mutation) {
    .Call('_PlantPopGenFIT_simulation', PACKAGE = 'PlantPopGenFIT', tsteps, mortality, demo, gt, K, dispersal, selfing, locus_effect, dominance_effect, phenotype_opt, n_p, n_k, mutation)
}

rcpp_hello_world <- function() {
    .Call('_PlantPopGenFIT_rcpp_hello_world', PACKAGE = 'PlantPopGenFIT')
}

