# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulation <- function(tsteps, mortality, demo, gt, K, seed_dispersal, pollen_dispersal, selfing, locus_effect, dominance_effect, phenotype_opt, n_p, n_k, mutation) {
    .Call('_PlantPopGenFIT_simulation', PACKAGE = 'PlantPopGenFIT', tsteps, mortality, demo, gt, K, seed_dispersal, pollen_dispersal, selfing, locus_effect, dominance_effect, phenotype_opt, n_p, n_k, mutation)
}

assign_reproductive_intensity_random <- function(num_ind, mean, sigma) {
    .Call('_PlantPopGenFIT_assign_reproductive_intensity_random', PACKAGE = 'PlantPopGenFIT', num_ind, mean, sigma)
}

assign_death_randomly_by_age_class <- function(mortality, demo) {
    .Call('_PlantPopGenFIT_assign_death_randomly_by_age_class', PACKAGE = 'PlantPopGenFIT', mortality, demo)
}

sample_with_replacement_based_on_relative_weights <- function(weights) {
    .Call('_PlantPopGenFIT_sample_with_replacement_based_on_relative_weights', PACKAGE = 'PlantPopGenFIT', weights)
}

recruit_to_carrying_capacity <- function(demo, mortality_individuals, K) {
    .Call('_PlantPopGenFIT_recruit_to_carrying_capacity', PACKAGE = 'PlantPopGenFIT', demo, mortality_individuals, K)
}

assign_mothers_of_recruits <- function(demo, recruit_demo, reproductive_intensity, dispersal) {
    .Call('_PlantPopGenFIT_assign_mothers_of_recruits', PACKAGE = 'PlantPopGenFIT', demo, recruit_demo, reproductive_intensity, dispersal)
}

assign_fathers_of_recruits <- function(demo, recruit_demo, reproductive_intensity, dispersal, mother_index, selfing) {
    .Call('_PlantPopGenFIT_assign_fathers_of_recruits', PACKAGE = 'PlantPopGenFIT', demo, recruit_demo, reproductive_intensity, dispersal, mother_index, selfing)
}

assign_alleles_to_recruits <- function(gt, mother_index, father_index) {
    .Call('_PlantPopGenFIT_assign_alleles_to_recruits', PACKAGE = 'PlantPopGenFIT', gt, mother_index, father_index)
}

row_bind_integer_matrices <- function(a, b) {
    .Call('_PlantPopGenFIT_row_bind_integer_matrices', PACKAGE = 'PlantPopGenFIT', a, b)
}

update_demo <- function(demo, mortality_individuals, recruit_demo) {
    .Call('_PlantPopGenFIT_update_demo', PACKAGE = 'PlantPopGenFIT', demo, mortality_individuals, recruit_demo)
}

update_gt <- function(gt, mortality_individuals, recruit_gt) {
    .Call('_PlantPopGenFIT_update_gt', PACKAGE = 'PlantPopGenFIT', gt, mortality_individuals, recruit_gt)
}

assign_phenotype_quantitative <- function(gt, locus_effect, dominance_effect) {
    .Call('_PlantPopGenFIT_assign_phenotype_quantitative', PACKAGE = 'PlantPopGenFIT', gt, locus_effect, dominance_effect)
}

assign_phenotype_quantitative_epistatic <- function(gt, locus_effect, dominance_effect, epistatic_effect) {
    .Call('_PlantPopGenFIT_assign_phenotype_quantitative_epistatic', PACKAGE = 'PlantPopGenFIT', gt, locus_effect, dominance_effect, epistatic_effect)
}

assign_reproductive_intensity_phenotype <- function(demo, phenotype_value, phenotype_opt, n_p, n_k) {
    .Call('_PlantPopGenFIT_assign_reproductive_intensity_phenotype', PACKAGE = 'PlantPopGenFIT', demo, phenotype_value, phenotype_opt, n_p, n_k)
}

mutate_genotypes <- function(gt, mutation) {
    .Call('_PlantPopGenFIT_mutate_genotypes', PACKAGE = 'PlantPopGenFIT', gt, mutation)
}

